"""
Rule definitions v1.0 — thresholds/weights sourced from DEMO policy configuration.
"""

from app.risk_engine.enums import RiskDimension, RuleOperator, RuleSeverity, RuleStatus
from app.risk_engine.models import RuleDefinition
from app.risk_engine.policy.demo_policy import DEMO_CATEGORICAL, DEMO_RULE_WEIGHTS, DEMO_THRESHOLDS

_RULE_VERSION = "1.0"


def _w(rule_id: str) -> float:
    return DEMO_RULE_WEIGHTS[rule_id]


def _t(rule_id: str) -> float | int:
    return DEMO_THRESHOLDS[rule_id]


RULES_V1_0: tuple[RuleDefinition, ...] = (
    # --- CREDIT ----------------------------------------------------------------
    RuleDefinition(
        rule_id="CREDIT_001",
        name="Low owner credit score (DEMO threshold)",
        dimension=RiskDimension.CREDIT,
        field="owner_credit_score",
        operator=RuleOperator.LESS_THAN,
        threshold=_t("CREDIT_001"),
        severity=RuleSeverity.HIGH,
        weight=_w("CREDIT_001"),
        description="Owner credit score below DEMO policy threshold — not production policy.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="CREDIT_002",
        name="Prior loan default recorded",
        dimension=RiskDimension.CREDIT,
        field="previous_defaults",
        operator=RuleOperator.GREATER_THAN,
        threshold=_t("CREDIT_002"),
        severity=RuleSeverity.HIGH,
        weight=_w("CREDIT_002"),
        description="Any recorded previous default (factual flag, threshold=0).",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="CREDIT_003",
        name="High credit utilization (DEMO threshold)",
        dimension=RiskDimension.CREDIT,
        field="credit_utilization_ratio",
        operator=RuleOperator.GREATER_THAN,
        threshold=_t("CREDIT_003"),
        severity=RuleSeverity.MEDIUM,
        weight=_w("CREDIT_003"),
        description="Credit utilization above DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="CREDIT_004",
        name="Elevated recent hard inquiries (DEMO threshold)",
        dimension=RiskDimension.CREDIT,
        field="recent_hard_inquiries_90d",
        operator=RuleOperator.GREATER_THAN,
        threshold=_t("CREDIT_004"),
        severity=RuleSeverity.MEDIUM,
        weight=_w("CREDIT_004"),
        description="Recent hard inquiries above DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="CREDIT_005",
        name="Limited credit history (DEMO threshold)",
        dimension=RiskDimension.CREDIT,
        field="age_oldest_trade_line_months",
        operator=RuleOperator.LESS_THAN,
        threshold=_t("CREDIT_005"),
        severity=RuleSeverity.LOW,
        weight=_w("CREDIT_005"),
        description="Oldest trade line age below DEMO policy threshold (months).",
        version=_RULE_VERSION,
    ),
    # --- FINANCIAL -------------------------------------------------------------
    RuleDefinition(
        rule_id="FIN_001",
        name="Negative operating cash flow",
        dimension=RiskDimension.FINANCIAL,
        field="operating_cash_flow",
        operator=RuleOperator.LESS_THAN,
        threshold=_t("FIN_001"),
        severity=RuleSeverity.MEDIUM,
        weight=_w("FIN_001"),
        description="Operating cash flow is negative (sign check, threshold=0).",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="FIN_002",
        name="Weak profitability (DEMO threshold)",
        dimension=RiskDimension.FINANCIAL,
        field="net_profit_margin",
        operator=RuleOperator.LESS_THAN,
        threshold=_t("FIN_002"),
        severity=RuleSeverity.MEDIUM,
        weight=_w("FIN_002"),
        description="Net profit margin below DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="FIN_003",
        name="Weak liquidity (DEMO threshold)",
        dimension=RiskDimension.FINANCIAL,
        field="current_ratio",
        operator=RuleOperator.LESS_THAN,
        threshold=_t("FIN_003"),
        severity=RuleSeverity.MEDIUM,
        weight=_w("FIN_003"),
        description="Current ratio below DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="FIN_004",
        name="High leverage (DEMO threshold)",
        dimension=RiskDimension.FINANCIAL,
        field="debt_to_equity_ratio",
        operator=RuleOperator.GREATER_THAN,
        threshold=_t("FIN_004"),
        severity=RuleSeverity.MEDIUM,
        weight=_w("FIN_004"),
        description="Debt-to-equity ratio above DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="FIN_005",
        name="Frequent NSF events (DEMO threshold)",
        dimension=RiskDimension.FINANCIAL,
        field="nsf_last_6_months",
        operator=RuleOperator.GREATER_THAN,
        threshold=_t("FIN_005"),
        severity=RuleSeverity.HIGH,
        weight=_w("FIN_005"),
        description="NSF count in last 6 months above DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="FIN_006",
        name="Elevated revenue volatility (DEMO threshold)",
        dimension=RiskDimension.FINANCIAL,
        field="revenue_volatility",
        operator=RuleOperator.GREATER_THAN,
        threshold=_t("FIN_006"),
        severity=RuleSeverity.MEDIUM,
        weight=_w("FIN_006"),
        description="Revenue volatility above DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="FIN_007",
        name="Large loan relative to revenue (DEMO threshold)",
        dimension=RiskDimension.FINANCIAL,
        field="loan_to_revenue_ratio",
        operator=RuleOperator.GREATER_THAN,
        threshold=_t("FIN_007"),
        severity=RuleSeverity.MEDIUM,
        weight=_w("FIN_007"),
        description="Loan amount / annual revenue above DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    # --- BUSINESS --------------------------------------------------------------
    RuleDefinition(
        rule_id="BUS_001",
        name="Limited operating history (DEMO threshold)",
        dimension=RiskDimension.BUSINESS,
        field="years_in_business",
        operator=RuleOperator.LESS_THAN,
        threshold=_t("BUS_001"),
        severity=RuleSeverity.MEDIUM,
        weight=_w("BUS_001"),
        description="Years in business below DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="BUS_002",
        name="High customer concentration (DEMO threshold)",
        dimension=RiskDimension.BUSINESS,
        field="customer_concentration",
        operator=RuleOperator.GREATER_THAN,
        threshold=_t("BUS_002"),
        severity=RuleSeverity.MEDIUM,
        weight=_w("BUS_002"),
        description="Customer concentration above DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    # --- DOCUMENT_COMPLIANCE (preserve DOC_001–003) ----------------------------
    RuleDefinition(
        rule_id="DOC_001",
        name="Forged documents detected",
        dimension=RiskDimension.DOCUMENT_COMPLIANCE,
        field="document_verification",
        operator=RuleOperator.EQUALS,
        threshold=DEMO_CATEGORICAL["DOC_001"],
        severity=RuleSeverity.CRITICAL,
        weight=_w("DOC_001"),
        description="Document verification rollup indicates forged documents.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="DOC_002",
        name="Missing critical documents",
        dimension=RiskDimension.DOCUMENT_COMPLIANCE,
        field="document_verification",
        operator=RuleOperator.EQUALS,
        threshold=DEMO_CATEGORICAL["DOC_002"],
        severity=RuleSeverity.HIGH,
        weight=_w("DOC_002"),
        description="Document verification rollup indicates missing critical documents.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="DOC_003",
        name="Individual document marked forged",
        dimension=RiskDimension.DOCUMENT_COMPLIANCE,
        field="ein_letter",
        operator=RuleOperator.EQUALS,
        threshold=DEMO_CATEGORICAL["DOC_003"],
        severity=RuleSeverity.HIGH,
        weight=_w("DOC_003"),
        description="EIN letter document status is Forged.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="DOC_004",
        name="Incomplete documentation (DEMO threshold)",
        dimension=RiskDimension.DOCUMENT_COMPLIANCE,
        field="completeness_score",
        operator=RuleOperator.LESS_THAN,
        threshold=_t("DOC_004"),
        severity=RuleSeverity.MEDIUM,
        weight=_w("DOC_004"),
        description="Completeness score below DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="DOC_005",
        name="Owner government ID missing",
        dimension=RiskDimension.DOCUMENT_COMPLIANCE,
        field="owner_gov_id",
        operator=RuleOperator.EQUALS,
        threshold=DEMO_CATEGORICAL["DOC_005"],
        severity=RuleSeverity.HIGH,
        weight=_w("DOC_005"),
        description="Owner government ID document is Missing.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="DOC_006",
        name="Bank statements missing",
        dimension=RiskDimension.DOCUMENT_COMPLIANCE,
        field="bank_statements_6mo",
        operator=RuleOperator.EQUALS,
        threshold=DEMO_CATEGORICAL["DOC_006"],
        severity=RuleSeverity.HIGH,
        weight=_w("DOC_006"),
        description="Six-month bank statements are Missing.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="DOC_007",
        name="Tax returns missing",
        dimension=RiskDimension.DOCUMENT_COMPLIANCE,
        field="tax_returns_2yrs",
        operator=RuleOperator.EQUALS,
        threshold=DEMO_CATEGORICAL["DOC_007"],
        severity=RuleSeverity.HIGH,
        weight=_w("DOC_007"),
        description="Two-year tax returns are Missing.",
        version=_RULE_VERSION,
    ),
    # --- MARKET_INDUSTRY -------------------------------------------------------
    RuleDefinition(
        rule_id="MKT_001",
        name="Adverse market condition (configured categories)",
        dimension=RiskDimension.MARKET_INDUSTRY,
        field="market_condition",
        operator=RuleOperator.IN,
        threshold=DEMO_CATEGORICAL["MKT_001"],
        severity=RuleSeverity.MEDIUM,
        weight=_w("MKT_001"),
        description="Market condition in configured adverse categories (Volatile, Recession).",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="MKT_002",
        name="Elevated local unemployment (DEMO threshold)",
        dimension=RiskDimension.MARKET_INDUSTRY,
        field="local_unemployment_rate",
        operator=RuleOperator.GREATER_THAN,
        threshold=_t("MKT_002"),
        severity=RuleSeverity.MEDIUM,
        weight=_w("MKT_002"),
        description="Local unemployment rate above DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="MKT_003",
        name="Weak industry growth forecast (DEMO threshold)",
        dimension=RiskDimension.MARKET_INDUSTRY,
        field="industry_growth_forecast",
        operator=RuleOperator.LESS_THAN,
        threshold=_t("MKT_003"),
        severity=RuleSeverity.LOW,
        weight=_w("MKT_003"),
        description="Industry growth forecast below DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    # --- REPUTATION_OPERATIONAL ------------------------------------------------
    RuleDefinition(
        rule_id="REP_001",
        name="Poor online rating (DEMO threshold)",
        dimension=RiskDimension.REPUTATION_OPERATIONAL,
        field="online_rating",
        operator=RuleOperator.LESS_THAN,
        threshold=_t("REP_001"),
        severity=RuleSeverity.LOW,
        weight=_w("REP_001"),
        description="Online rating below DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="REP_002",
        name="Low review volume (DEMO threshold)",
        dimension=RiskDimension.REPUTATION_OPERATIONAL,
        field="review_volume",
        operator=RuleOperator.LESS_THAN,
        threshold=_t("REP_002"),
        severity=RuleSeverity.INFO,
        weight=_w("REP_002"),
        description="Review volume below DEMO policy threshold.",
        version=_RULE_VERSION,
    ),
    RuleDefinition(
        rule_id="REP_003",
        name="Inactive website presence",
        dimension=RiskDimension.REPUTATION_OPERATIONAL,
        field="website_active",
        operator=RuleOperator.EQUALS,
        threshold=DEMO_CATEGORICAL["REP_003"],
        severity=RuleSeverity.INFO,
        weight=_w("REP_003"),
        description="Website is not active.",
        version=_RULE_VERSION,
    ),
)
